/*
* SPDX-License-Identifier: LGPL-3.0-or-later
* Copyright © 2026 BotForge
*/

import { Guild, GuildMFALevel, GuildNSFWLevel, GuildPreview, GuildVerificationLevel } from "discord.js"
import defineProperties from "../functions/defineProperties"

export enum GuildProperty {
    id = "id",
    ownerID = "ownerID",
    name = "name",
    nameAcronym = "nameAcronym",
    description = "description",
    timestamp = "timestamp",
    features = "features",
    icon = "icon",
    banner = "banner",
    splash = "splash",
    discoverySplash = "discoverySplash",
    afkTimeout = "afkTimeout",
    afkChannelID = "afkChannelID",
    systemChannelID = "systemChannelID",
    systemChannelFlags = "systemChannelFlags",
    publicUpdatesChannelID = "publicUpdatesChannelID",
    safetyAlertsChannelID = "safetyAlertsChannelID",
    rulesChannelID = "rulesChannelID",
    widgetChannelID = "widgetChannelID",
    widgetEnabled = "widgetEnabled",
    bans = "bans",
    roles = "roles",
    emojis = "emojis",
    stickers = "stickers",
    channels = "channels",
    soundboardSounds = "soundboardSounds",
    autoModerationRules = "autoModerationRules",
    memberCount = "memberCount",
    boostCount = "boostCount",
    boostLevel = "boostLevel",
    mfaLevel = "mfaLevel",
    nsfwLevel = "nsfwLevel",
    verificationLevel = "verificationLevel",
    preferredLocale = "preferredLocale",
    large = "large",
    verified = "verified",
    partnered = "partnered",
    maximumMembers = "maximumMembers",
    maximumStageBitrate = "maximumStageBitrate",
    approximateMemberCount = "approximateMemberCount",
    approximatePresenceCount = "approximatePresenceCount",
}

export const GuildProperties = defineProperties<typeof GuildProperty, Guild>({
    id: (i) => i?.id,
    ownerID: (i) => i?.ownerId,
    name: (i) => i?.name,
    nameAcronym: (i) => i?.nameAcronym,
    description: (i) => i?.description,
    timestamp: (i) => i?.createdTimestamp,
    features: (i, sep) => i?.features.join(sep ?? ", "),
    icon: (i) => i?.iconURL(),
    banner: (i) => i?.bannerURL(),
    splash: (i) => i?.splashURL(),
    discoverySplash: (i) => i?.discoverySplashURL(),
    afkTimeout: (i) => i?.afkTimeout,
    afkChannelID: (i) => i?.afkChannelId,
    systemChannelID: (i) => i?.systemChannelId,
    systemChannelFlags: (i, sep) => i?.systemChannelFlags.toArray().join(sep ?? ", "),
    publicUpdatesChannelID: (i) => i?.publicUpdatesChannelId,
    safetyAlertsChannelID: (i) => i?.safetyAlertsChannelId,
    rulesChannelID: (i) => i?.rulesChannelId,
    widgetChannelID: (i) => i?.widgetChannelId,
    widgetEnabled: (i) => i?.widgetEnabled,
    bans: (i, sep) => i?.bans.cache.map((x) => x.user.id).join(sep ?? ", "),
    roles: (i, sep) => i?.roles.cache.map((x) => x.id).join(sep ?? ", "),
    emojis: (i, sep) => i?.emojis.cache.map((x) => x.id).join(sep ?? ", "),
    stickers: (i, sep) => i?.stickers.cache.map((x) => x.id).join(sep ?? ", "),
    channels: (i, sep) => i?.channels.cache.map((x) => x.id).join(sep ?? ", "),
    soundboardSounds: (i, sep) => i?.soundboardSounds.cache.map((x) => x.soundId).join(sep ?? ", "),
    autoModerationRules: (i, sep) => i?.autoModerationRules.cache.map((x) => x.id).join(sep ?? ", "),
    memberCount: (i) => i?.memberCount,
    boostCount: (i) => i?.premiumSubscriptionCount,
    boostLevel: (i) => i?.premiumTier,
    mfaLevel: (i) => i?.nsfwLevel ? GuildMFALevel[i.mfaLevel] : null,
    nsfwLevel: (i) => i?.nsfwLevel ? GuildNSFWLevel[i.nsfwLevel] : null,
    verificationLevel: (i) => i?.verificationLevel ? GuildVerificationLevel[i.verificationLevel] : null,
    preferredLocale: (i) => i?.preferredLocale,
    large: (i) => i?.large,
    verified: (i) => i?.verified,
    partnered: (i) => i?.partnered,
    maximumMembers: (i) => i?.maximumMembers,
    maximumStageBitrate: (i) => i?.maximumStageBitrate,
    approximateMemberCount: (i) => i?.approximateMemberCount,
    approximatePresenceCount: (i) => i?.approximatePresenceCount,
})

export enum GuildPreviewProperty {
    id = "id",
    name = "name",
    description = "description",
    features = "features",
    timestamp = "timestamp",
    icon = "icon",
    splash = "splash",
    emojis = "emojis",
    stickers = "stickers",
    discoverySplash = "discoverySplash",
    approximateMemberCount = "approximateMemberCount",
    approximatePresenceCount = "approximatePresenceCount",
}

export const GuildPreviewProperties = defineProperties<typeof GuildPreviewProperty, GuildPreview>({
    id: (i) => i?.id,
    name: (i) => i?.name,
    description: (i) => i?.description,
    features: (i, sep) => i?.features.join(sep || ", "),
    timestamp: (i) => i?.createdTimestamp,
    icon: (i) => i?.iconURL(),
    splash: (i) => i?.splashURL(),
    emojis: (i, sep) => i?.emojis.map((x) => x.id).join(sep || ", "),
    stickers: (i, sep) => i?.stickers.map((x) => x.id).join(sep || ", "),
    discoverySplash: (i) => i?.discoverySplashURL(),
    approximateMemberCount: (i) => i?.approximateMemberCount,
    approximatePresenceCount: (i) => i?.approximatePresenceCount,
})