name: tsc
on:
  pull_request:
  push:
jobs:
  tsc:
    name: Run tsc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tsc
        run: npx tsc